// M6/deliveroo/customer-portal/features/auth/forgot-password/ForgotPassword.vue
<template>
  <div>
    <div class="text-center mb-6">
      <h2 class="text-3xl font-bold text-gray-900 dark:text-white">
        Reset your password
      </h2>
      <p class="mt-2 text-sm text-gray-600 dark:text-gray-400">
        Enter your email address and we'll send you a link to reset your password.
      </p>
    </div>

    <div v-if="!emailSent">
      <form @submit.prevent="handleForgotPassword" class="space-y-6">
        <div>
          <label for="email" class="block text-sm font-medium text-gray-700 dark:text-gray-300">
            Email address
          </label>
          <input
            id="email"
            v-model="form.email"
            type="email"
            required
            autocomplete="email"
            class="input"
            placeholder="Enter your email address"
          />
        </div>

        <div>
          <button
            type="submit"
            :disabled="loading"
            class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            <span v-if="!loading">Send reset instructions</span>
            <span v-else class="flex items-center">
              <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              Sending...
            </span>
          </button>
        </div>

        <div class="text-center">
          <NuxtLink to="/login" class="text-sm font-medium text-primary-600 hover:text-primary-500 dark:text-primary-400">
            ← Back to sign in
          </NuxtLink>
        </div>
      </form>
    </div>

    <!-- Success State -->
    <div v-else class="text-center">
      <div class="mx-auto flex items-center justify-center h-16 w-16 rounded-full bg-green-100 dark:bg-green-900 mb-4">
        <svg class="h-8 w-8 text-green-600 dark:text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
        </svg>
      </div>
      
      <h3 class="text-lg font-medium text-gray-900 dark:text-white mb-2">
        Check your email
      </h3>
      
      <p class="text-sm text-gray-600 dark:text-gray-400 mb-6">
        We've sent password reset instructions to <strong>{{ form.email }}</strong>
      </p>
      
      <div class="space-y-3">
        <p class="text-xs text-gray-500 dark:text-gray-400">
          Didn't receive the email? Check your spam folder or
        </p>
        
        <button
          @click="resetForm"
          class="text-sm font-medium text-primary-600 hover:text-primary-500 dark:text-primary-400"
        >
          Try again with a different email
        </button>
        
        <div class="border-t border-gray-200 dark:border-gray-700 pt-4">
          <NuxtLink to="/login" class="text-sm font-medium text-primary-600 hover:text-primary-500 dark:text-primary-400">
            ← Back to sign in
          </NuxtLink>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { forgotPassword } from './forgot-password-api'
import type { ForgotPasswordFormData } from './forgot-password.model'

interface Emits {
  (e: 'success', message: string): void
  (e: 'error', error: string): void
}

const emit = defineEmits<Emits>()

const loading = ref(false)
const emailSent = ref(false)

const form = reactive<ForgotPasswordFormData>({
  email: ''
})

const handleForgotPassword = async () => {
  loading.value = true
  
  try {
    const result = await forgotPassword(form)
    emailSent.value = true
    emit('success', result.message)
  } catch (error) {
    emit('error', error instanceof Error ? error.message : 'Failed to send reset email')
    console.error('Forgot password failed:', error)
  } finally {
    loading.value = false
  }
}

const resetForm = () => {
  emailSent.value = false
  form.email = ''
}
</script>

// M6/deliveroo/wms-frontend/src/app/auth/forgot-password/forgot-password.component.ts
import { Component, inject, signal, output, WritableSignal } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthService } from '../auth.service';
import { Heading2Component } from '../../ui-library/Typography/Typography.component';

@Component({
  selector: 'app-forgot-password',
  standalone: true,
  imports: [ReactiveFormsModule, Heading2Component],
  template: `
    <div class="flex items-center justify-center min-h-[400px]">
      <div class="card p-8 w-full max-w-md bg-white rounded-lg shadow-lg animate-fade-in">
        <div class="text-center mb-8">
          <div class="mx-auto h-16 w-16 bg-primary-600 rounded-lg flex items-center justify-center mb-4">
            <svg class="h-8 w-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
            </svg>
          </div>
          <ui-heading2 class="text-neutral-800">Forgot Password</ui-heading2>
          <p class="mt-2 text-neutral-600">Enter your email and we'll send you a reset link</p>
        </div>

        @if (submitted()) {
          <div class="bg-success-50 text-success-500 p-4 rounded-md mb-6 animate-fade-in">
            <p class="text-center font-medium">Reset link sent!</p>
            <p class="text-center text-sm mt-2">If an account exists with this email, you will receive password reset instructions.</p>
          </div>

          <div class="text-center mt-6">
            <button (click)="onBackToLogin()" class="btn btn-primary w-full">
              Return to Login
            </button>
          </div>
        } @else {
          <form [formGroup]="forgotPasswordForm" (ngSubmit)="onSubmit()" class="space-y-6">
            <div>
              <label for="email" class="block text-sm font-medium text-gray-700 dark:text-gray-300">Email</label>
              <input 
                type="email" 
                id="email" 
                formControlName="email"
                class="input mt-1"
                autocomplete="email" 
                [class.border-error-500]="isFieldInvalid('email')" />
              @if (isFieldInvalid('email')) {
                <p class="mt-1 text-sm text-error-500">Please enter a valid email address</p>
              }
            </div>
            <div>
              <button 
                type="submit" 
                [disabled]="isLoading() || !forgotPasswordForm.valid"
                class="btn btn-primary w-full py-3 flex justify-center items-center">
                @if (isLoading()) {
                  <span class="mr-2">
                    <span class="animate-spin inline-block w-4 h-4 border-2 border-white border-t-transparent rounded-full"></span>
                  </span>
                }
                Send Reset Link
              </button>
            </div>
            <div class="text-center mt-4">
              <a (click)="onBackToLogin()" class="cursor-pointer text-primary-500 hover:text-primary-600 transition-colors">
                Back to Login
              </a>
            </div>
          </form>
        }
      </div>
    </div>
  `
})
export class ForgotPasswordComponent {
  private fb = inject(FormBuilder);
  private authService = inject(AuthService);

  forgotPasswordForm: FormGroup;
  isLoading: WritableSignal<boolean> = signal(false);
  submitted: WritableSignal<boolean> = signal(false);

  backToLogin = output<void>();

  constructor() {
    this.forgotPasswordForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]]
    });
  }

  isFieldInvalid(field: string): boolean {
    const formControl = this.forgotPasswordForm.get(field);
    return formControl !== null && formControl.invalid && (formControl.dirty || formControl.touched);
  }

  onSubmit(): void {
    if (this.forgotPasswordForm.valid) {
      this.isLoading.set(true);
      const email = this.forgotPasswordForm.get('email')?.value;
      this.authService.forgotPassword(email).subscribe(() => {
        this.isLoading.set(false);
        this.submitted.set(true);
      });
    } else {
      this.forgotPasswordForm.markAllAsTouched();
    }
  }

  onBackToLogin(): void {
    this.backToLogin.emit();
  }
}
